pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh """
                    set -e
                    npm config set proxy http://web-proxy.houston.softwaregrp.net:8080
                    npm config set https-proxy http://web-proxy.houston.softwaregrp.net:8080
                    mvn -B -DskipTests clean package
                """
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
